### ISSUE TITLE
Is there a way i can publish nunit xml results to powerbi directly?

### ISSUE THREAD

**Issue by gnaneswarreddy** [CharliePoole/nunit-results#14]

**Comment by CharliePoole** [comment]
You haven't given much explanation of what you want, but I think you're asking the question in the wrong place...

1. It doesn't seem to be about this project...

    "NUnit-Results is a console application used to produce HTML reports from the 
    output of NUnit test runs. It is part of the NUnit.Extras suite."

2. This project formats reports from the NUnit V2 XML output, which is most-likely not what you are using.

3. I think it's really a question about Power BI - which is not something I know anything about. :disappointed:

**Comment by CharliePoole** [comment]
Closing this question but if you re-post, I'll see it.
